name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - run: |
          sudo netstat -tulpn
          sudo wget -O /etc/apt/sources.list.d/bedrock.list https://apt.bedrockdb.com/ubuntu/dists/$(lsb_release -cs)/bedrock.list
          wget -O - https://apt.bedrockdb.com/bedrock.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install bedrock
          touch bedrock.db
          sudo netstat -tulpn
          sudo pkill bedrock
          sleep 3
          sudo netstat -tulpn
          #mysqladmin -h 127.0.0.1 -u root -proot status
      - run: cat /var/log/syslog
        if: ${{ always() }}
      - run: cat bedrock.db
        if: ${{ always() }}
      - run: cat /var/lib/bedrock/bedrock.db
        if: ${{ always() }}
